import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/navbar">Navbar</Link>
        </li>
        <li>
          <Link to="/">Landingpage</Link>
        </li>
        <li>
          <Link to="/volunteer">Volunteer</Link>
        </li>
        <li>
          <Link to="/article">Article</Link>
        </li>
        <li>
          <Link to="/donation">Donation</Link>
        </li>
        <li>
          <Link to="/listhewandilindungi">ListHewandilindungi</Link>
        </li>
        <li>
          <Link to="/signuppage">SignupPage</Link>
        </li>
        <li>
          <Link to="/laporan">Laporan</Link>
        </li>
        <li>
          <Link to="/loginpage">LoginPage</Link>
        </li>
        <li>
          <Link to="/articlelist">Articlelist</Link>
        </li>
        <li>
          <Link to="/detaildonationtwo">DetailDonationTwo</Link>
        </li>
        <li>
          <Link to="/detailhewandilindungi">DetailHewandilindungi</Link>
        </li>
        <li>
          <Link to="/detailvolunteer">DetailVolunteer</Link>
        </li>
        <li>
          <Link to="/detaildonation">DetailDonation</Link>
        </li>
        <li>
          <Link to="/detailhewandilindungitwo">DetailHewandilindungiTwo</Link>
        </li>
        <li>
          <Link to="/detaildonationone">DetailDonationOne</Link>
        </li>
        <li>
          <Link to="/formvolunteersuccess">FormVolunteerSuccess</Link>
        </li>
        <li>
          <Link to="/formvolunteer">FormVolunteer</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
